version: "3.7"

services:
  ratingsDB:
    hostname: ratingsDB  
    image: project/mysql
    build: ./
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ratingsDB
    volumes:
      # This creates an anonymous volume associated with this container
      # to clear it, run with "-V", docker compose up --build -V
      - /var/lib/mysql
    networks:
      - project

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - project

networks:
  project:
    external: true
